name: Run script

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Run script
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.0'

      - name: Setting up bun
        uses: oven-sh/setup-bun@v1

      - name: Installing dependencies
        run: bun install

      - name: Run script
        run: bun run start
